calc/urls.py
from django.conf.urls import url

from . import views

app_name = 'calc'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^$', views.result, name='result'),
    # url(r'^(?P<question>[0-9]+)/$', views.result, name='result'),
    url(r'^(?P<test>[0-9]+)/result/$', views.result, name='result'),
    # url(r'^$', views.result, name='result'),
]

newCalc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^calc/', include('calc.urls')),
    url(r'^admin/', admin.site.urls),
]

calc/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

calc/views.py
from django.http import HttpResponse
from .models import Question
from django.shortcuts import render
from math import pi

def index(request):
    return render(request, 'calc/index.html')

# def result(request, can_height):
#     return render(request, 'calc/result.html', {'canHeight': can_height})

# def result(request):
#     if request.method == "POST":
#         list_values = request.POST.getlist('my_list')
#     return render(request, 'calc/result.html', {'list': list_values})

def result(request, test):
    if request.method == "GET":
        can_height= request.GET['canHeight']
        can_radius = request.GET['canRadius']
    tuple = calculate(float(can_radius), float(can_height))
    return render(request, 'calc/result.html', {
        'canHeight': can_height,
        'canRadius': can_radius,
        'tuple': tuple,
        'wastedSpace': tuple[1],
        'numOfCans': tuple[0]
    })


def calculate(Cd, Ch ):
    # Cd = 0.02
    # Ch = 0.10
    # volume of can/box
    Vb = (Cd * Cd * Ch)
    Vs = 32.2514

    # maximun number of cans that will fit in the shipping container
    maxCans = int(Vs / Vb)
    print("maximun number of cans that will fit in the shipping container: ", maxCans)

    wasteSp = (32.2514 - (maxCans * Ch * pi * (Cd / 2) ** 2))
    # volume of wasted space
    print("volume of wasted space: ", wasteSp, "m^3")

    return (maxCans, wasteSp)
    # General concensus: long skinny cans create less wasted space.

calc/templates/calc/index.html
<h1>Calculus Canning Calculator</h1>

<form action="{% url 'calc:result' 100 %}" method="get">
{% csrf_token %}
    <label>Shipping Container Volume: 32.2514 m^3</label><br>
    <label>Can Height: </label>
    <input type="text" name="canHeight" id="02" value="" /><br>
    <label>Can Radius: </label>
    <input type="text" name="canRadius" id="03" value="" /><br>
    <input type="submit" value="Crunch The Numbers" />
</form>

calc/templates/calc/result.html
<h1>Result Page</h1>

<label>Can Height: {{ canHeight }}</label> <br>
<label>Can Radius: {{ canRadius }}</label> <br><br>

<label>Number of cans: {{ numOfCans}} </label><br>
<label>Wasted Space: {{ wastedSpace}} </label><br>